# Generated by Django 5.0 on 2024-01-24 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adresse',
            name='avocat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.avocat'),
        ),
        migrations.CreateModel(
            name='DomaineSpecialisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60)),
                ('avocat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.avocat')),
            ],
        ),
    ]
