# Generated by Django 5.0 on 2024-01-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_adresse_avocat_domainespecialisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='avocat',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='avocat',
            name='password',
            field=models.CharField(default='default@example.com', max_length=255),
        ),
    ]
