# Generated by Django 5.0 on 2024-01-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_avocat_email_avocat_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='avocat',
            name='langue',
            field=models.CharField(default='francais', max_length=255),
        ),
    ]
