# Generated by Django 5.0 on 2024-01-25 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_address_remove_rendezvous_avocat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawyerprofile',
            name='address',
        ),
    ]
