# Generated by Django 5.0 on 2024-01-25 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_lawyerprofile_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='address',
        ),
    ]
