# Generated by Django 5.0 on 2024-01-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_clientprofile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyerprofile',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
